### ISSUE TITLE
ソースコードのLicense決定

### ISSUE THREAD

**Issue by yumetodo** [takeokunn/DoNotPushGame#12]
個人的にはMIT Licenseにしていいと思っている。

**Comment by newYuchu8** [comment]
いいよ

**Comment by yumetodo** [comment]
<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/yumetodo">@yumetodo</a> MITでいいんじゃない？</p>&mdash; たけてぃ (@takeokunn) <a href="https://twitter.com/takeokunn/status/769415626599325696">2016年8月27日</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by yumetodo** [comment]
エンディングの音声にGoogle翻訳の音声を使っていたがまずいので
https://github.com/takeokunn/DoNotPushGame/commit/2ca065197951a357d7f9e4dc88ef3a6c7eea99f5
で別の音源に差し替えた。

結果
https://github.com/takeokunn/DoNotPushGame/blob/master/License.md
のようにした。

画像は暫定でCC BY-SA、DTMに作ってもらった音声はCC BY-NDにしてある。
